name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang-tidy clang-format cmake make g++

    

      - name: Run clang-tidy
        run: |
          clang-tidy $(find . -name "*.cpp") -- -I . || true

  

      - name: Configure CMake, build project
        run: |
          cd Chess
          mkdir build
          cd build
          cmake ..
          make
